-- Storefront CMS and platform defaults (served via API; editable in admin).
INSERT INTO app_settings (key, value, updated_at) VALUES
(
	'storefront',
	$json${"featured_codes":["000078","000077","000079","000082","000085","000006","000001","000076","000021"],"part_codes":{"cpu":"000076","ram":"000032","ssd":"000006"},"content":{"trust":[{"icon":"bolt","title":"Resposta rápida"},{"icon":"globe","title":"Envios para toda a LATAM"},{"icon":"box","title":"+10.000 produtos disponíveis"},{"icon":"shield","title":"Garantia em todos os produtos"},{"icon":"headset","title":"Suporte técnico especializado"},{"icon":"refresh","title":"Equipamentos novos e refurbished"}],"pillars":[{"title":"Sourcing global","text":"Obtemos equipamentos difíceis de encontrar, novos ou refurbished, nos maiores mercados tecnológicos."},{"title":"Preços competitivos","text":"Negociamos direto com distribuidores e atacadistas para oferecer o melhor custo."},{"title":"Garantia real","text":"Todos os equipamentos passam por revisão técnica e contam com garantia."},{"title":"Entrega internacional","text":"Enviamos do Paraguai para toda a América Latina com rapidez e segurança."},{"title":"Atendimento técnico","text":"Assessoria para escolher o servidor, storage ou switch ideal para o seu projeto."},{"title":"Inventário amplo","text":"+10.000 SKUs disponíveis sob pedido."}],"steps":[{"title":"Passo 1 — Você solicita a cotação","text":"Envie o modelo, marca ou o requisito técnico do servidor, storage ou switch."},{"title":"Passo 2 — Localizamos o produto","text":"Buscamos na nossa rede global de fornecedores para garantir disponibilidade e o melhor preço."},{"title":"Passo 3 — Enviamos a proposta","text":"Você recebe uma proposta clara com especificações, preço, prazos e condições."},{"title":"Passo 4 — Envio internacional","text":"Despachamos do Paraguai com embalagem segura e documentação completa."},{"title":"Passo 5 — Garantia e suporte","text":"Todos os equipamentos incluem garantia e acompanhamento pós-venda."}],"faqs":[{"q":"Trabalham com equipamentos novos e recondicionados?","a":"Sim. Oferecemos equipamentos novos, usados e refurbished, sempre verificados e com garantia."},{"q":"Fazem envios internacionais?","a":"Sim. Enviamos do Paraguai para toda a América Latina."},{"q":"Posso solicitar um produto específico que não aparece no site?","a":"Sim. Fazemos sourcing global para encontrar modelos específicos conforme a sua necessidade."},{"q":"Os produtos têm garantia?","a":"Todos os equipamentos têm garantia e revisão técnica antes do despacho."},{"q":"Atendem empresas, datacenters e MSPs?","a":"Sim. Trabalhamos com integradores, MSPs, datacenters e empresas de todos os portes."}]}}$json$,
	NOW()
),
(
	'platform_defaults',
	$json${"warehouse_id":"11111111-1111-1111-1111-111111111001","location_id":"22222222-2222-2222-2222-222222222001","category_id":"55555555-5555-5555-5555-555555555001"}$json$,
	NOW()
)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;
