/** Barrel re-export — domain modules live in ./api/*. */
export {
  ApiClientError,
  addToCart,
  checkout,
  checkoutApi,
  catalogApi,
  cartApi,
  confirmPaymentIntent,
  fetchCart,
  fetchCatalog,
  fetchCategories,
  fetchPaymentConfig,
  fetchProduct,
  getMyOrder,
  listMyOrders,
  normalizeOrderNumber,
  quoteApi,
  requestShopLoginCode,
  shopAuthApi,
  submitQuote,
  updateCartItem,
  verifyShopLoginCode,
  type CheckoutPayload,
  type CheckoutResult,
  type PaymentConfig,
  type PaymentIntent,
  type QuotePayload,
  type ShopAuthTokens,
} from "./api/index";
